apiVersion: v1
kind: ConfigMap
metadata:
  name: documind-config
  namespace: documind
data:
  DJANGO_ENV: "production"
  POSTGRES_DB: "documind"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis-service:6379/0"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  QDRANT_HOST: "qdrant-service"
  QDRANT_PORT: "6333"
  QDRANT_GRPC_PORT: "6334"
  ALLOWED_HOSTS: "*"
  LLM_PROVIDER: "azure_openai"
