apiVersion: v1
kind: Service
metadata:
  name: documind-api-service
  namespace: documind
  labels:
    app: documind-api
spec:
  type: ClusterIP
  selector:
    app: documind-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
