apiVersion: v1
kind: Secret
metadata:
  name: documind-secrets
  namespace: documind
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "CHANGE-ME-use-kubectl-create-secret"
  POSTGRES_USER: "documind"
  POSTGRES_PASSWORD: "CHANGE-ME"
  AZURE_OPENAI_API_KEY: "CHANGE-ME"
  AZURE_OPENAI_ENDPOINT: "CHANGE-ME"
  AWS_ACCESS_KEY_ID: "CHANGE-ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE-ME"
  QDRANT_API_KEY: ""
